config {
  type: "table",
  schema: "capstone_data_model",
  description: "Final dimensional aggregation of dim_claims",
  assertions: {
    nonNull: ["clm_id"],
    uniqueKey: ["clm_id"]
  }
}

select
      ac.clm_id 
    , ac.bene_id 
    , ac.claim_file
    , ac.nch_clm_type_cat
    , ac.claim_processing_type
    , ac.is_inpatient_claim
    , ac.is_outpatient_claim
    , ac.is_durable_medical_equipment_claim
    , ac.is_hospice_claim
    , ac.is_home_health_agency_claim
    , ac.is_skilled_nursing_facility_claim
    , ac.clm_from_dt
    , ac.clm_thru_dt
    , ac.claim_start_year
    , ac.claim_end_year
    , ac.claim_duration_in_days
    , ac.clm_pmt_amt
    , pct.clm_pmt_per_rank_tot
    , pct.clm_pmt_per_rank_file
    , ac.carr_clm_prvdr_asgnmt_bool
    , ac.prncpal_dgns_cd
    , coalesce(ac.org_npi_num,0)                                as org_npi_num
    , ac.clm_fac_type_cat
    , ac.claim_is_in_hospital
    , ac.clm_srvc_clsfctn_type_cat
    , ac.clm_freq_cat
    , ac.clm_tot_chrg_amt
    , coalesce(ac.fst_dgns_e_cd,'N/A')                          as fst_dgns_e_cd 
    , ac.claim_has_external_cause
    , ac.clm_hha_tot_visit_cnt
    , coalesce(ac.clm_admsn_dt, date(1,1,1))                    as clm_admsn_dt
    , ac.clm_utlztn_day_cnt
    , coalesce(ac.nch_bene_dschrg_dt, date(1,1,1))              as nch_bene_dschrg_dt
    , coalesce(ac.clm_hospc_start_dt_id, date(1,1,1))           as clm_hospc_start_dt_id
    , ac.admission_is_emergency
    , ac.admission_is_urgent
    , ac.admission_is_elective
    , ac.clm_src_ip_admsn_cat
    , ac.clm_pass_thru_per_diem_amt
    , ac.nch_bene_ip_ddctbl_amt
    , ac.nch_bene_pta_coinsrnc_lblty_am
    , ac.nch_bene_blood_ddctbl_lblty_am
    , ac.nch_profnl_cmpnt_chrg_amt
    , ac.clm_tot_pps_cptl_amt
    , ac.clm_pps_cptl_dsprptnt_shr_amt
    , ac.clm_pps_cptl_excptn_amt
    , ac.clm_pps_cptl_fsp_amt
    , ac.clm_pps_cptl_ime_amt
    , ac.clm_pps_cptl_outlier_amt
    , ac.clm_pps_old_cplt_hld_hrmls_amt
    , ac.clm_pps_cptl_drg_wt_num
    , ac.bene_tot_coinsrnc_days_cnt
    , ac.clm_non_utlztn_days_cnt
    , ac.nch_blood_pnts_frnshd_qty
    , ac.clm_drg_outlier_stay_cat
    , ac.nch_drg_outlier_aprvd_pmt_amt
    , coalesce(ac.admtg_dgns_cd,'No Code')          as admtg_dgns_cd
    , ac.nch_bene_ptb_coinsrnc_amt
    , ac.nch_bene_partb_ddctbl_amt
    , ac.clm_op_prvdr_pmt_amt
    , ac.nch_carr_clm_sbmtd_chrg_amt
    , ac.nch_clm_prvdr_pmt_amt
    , ac.nch_ip_ncvrd_chrg_amt
    , ac.carr_clm_cash_ddctbl_apld_amt
    , ac.nch_carr_clm_alowd_amt
    , ac.nch_prmry_pyr_clm_pd_amt
from ${ref("int_all_claims_union")} ac 
left join ${ref("int_percentile_rank_clms_amt")} pct 
    on ac.clm_id = pct.clm_id