config {
  type: "table",
  schema: "capstone_intermediaries",
  description: "Intermediary cleansing of beneficiary 2020 source data",
  assertions: {
    nonNull: ["bene_id"],
    uniqueKey: ["bene_id"]
  }
}

select
    bene_id
  , bene_birth_dt
  , bene_death_dt
  , case 
      when bene_death_dt is not null 
        then True 
      else False 
      end                             as beneficiary_is_deceased
  , case 
      when sex_ident_cd = 1
        then 'Male'
      when sex_ident_cd = 2
        then 'Female'
      else 'Sex Unknown'
      end                             as sex_ident_cat
  , case 
      when sex_ident_cd = 1
        then True
      else False
      end                             as beneficiary_is_male
  , case 
      when sex_ident_cd = 2
        then True 
      else False  
      end                             as beneficiary_is_female
  , case 
      when bene_race_cd = 1 
        then 'Non-Hispanic White'
      when bene_race_cd = 2
        then 'Black'
      when bene_race_cd = 3
        then 'Other'
      when bene_race_cd = 4
        then 'Asian or Pacific Islander'
      when bene_race_cd = 5
        then 'Hispanic'
      when bene_race_cd = 6
        then 'Indigenous'
      else 'Unknown'
      end                             as bene_race_cat
    , case 
        when rti_race_cd = 1
          then 'Non-Hispanic White'
        when rti_race_cd = 2
          then 'Black'
        when rti_race_cd = 3
          then 'Other'
        when rti_race_cd = 4
          then 'Asian or Pacific Islander'
        when rti_race_cd = 5
          then 'Hispanic'
        when rti_race_cd = 6
          then 'Indigenous'
        else 'Unknown'
        end                           as rti_race_cat
    , case 
        when bene_race_cd = 1 or rti_race_cd = 1
          then True 
        else False 
        end                           as beneficiary_is_white
    , case 
        when bene_race_cd = 1 or rti_race_cd = 1
          then False 
        else True 
        end                           as beneficiary_is_not_white
    , case 
        when bene_race_cd = 2 or rti_race_cd = 2
          then True 
        else False 
        end                           as beneficiary_is_black
    , case
        when bene_race_cd = 4 or rti_race_cd = 4
          then True 
        else False 
        end                           as beneficiary_is_asian
    , case 
        when bene_race_cd = 5 or rti_race_cd = 5
          then True 
        else False 
        end                           as beneficiary_is_hispanic
    , case 
        when bene_race_cd = 6 or rti_race_cd = 6
          then True 
        else False 
        end                           as beneficiary_is_indigenous
    , case 
        when bene_race_cd = 3 or rti_race_cd = 3
          then True 
        else False 
        end                           as beneficiary_is_other_race
    , covstart
    , 2020                            as file_year
from ${ref("bene_20")}