config {
  type: "table",
  schema: "capstone_intermediaries",
  description: "Initial cleaning of claims data - DME file",
  assertions: {
    nonNull: ["clm_id"],
    uniqueKey: ["clm_id"]
  }
}

--bringing in claim-level-only rows, do a group by all to aggregate. 
--Awkward but this table is at the line level instead of claim

--note that not all fields are used in all files, 
--so each file's interim processing may have manually-entered placeholders rendering to null, False, or 0 
--depending on data type

select 
      clm_id 
    , bene_id
    , 'DME'                                 as claim_file
    , 'DMERC DMEPOS'                        as nch_clm_type_cat
    , 'Regional carrier DMEPOS processed'   as claim_processing_type
    , False                                 as is_inpatient_claim 
    , False                                 as is_outpatient_claim
    , True                                  as is_durable_medical_equipment_claim
    , False                                 as is_hospice_claim
    , False                                 as is_home_health_agency_claim
    , False                                 as is_skilled_nursing_facility_claim
    , max(clm_from_dt)                      as clm_from_dt --not on claim level for dme
    , max(clm_thru_dt)                      as clm_thru_dt --not on claim level for dme
    , extract(year from clm_from_dt)        as claim_start_year
    , extract(year from clm_thru_dt)        as claim_end_year
    , date_diff(clm_thru_dt,clm_from_dt,day) as claim_duration_in_days
    , clm_pmt_amt
    --add percentile rankings in interim step after all claims are combined, then join to dimension
    , case 
        when carr_clm_prvdr_asgnmt_ind_sw = 'A'
            then True 
        else False 
        end                                 as carr_clm_prvdr_asgnmt_bool
    , prncpal_dgns_cd
    --count diagnoses: calculate in interim step after walk, then join to dimension
    , clm_clncl_tril_num
    , case 
        when clm_clncl_tril_num is not null 
            then True 
        else False 
        end                                 as claim_part_of_clinical_trial
    , null                                  as org_npi_num
    , 'No Facility Type'                    as clm_fac_type_cat
    , False                                 as claim_is_in_hospital
    , 'No Facility Classification Type'     as clm_srvc_clsfctn_type_cat
    , 'No Claim Frequency'                  as clm_freq_cat
    , 'No Nonpayment Reason'                as clm_mdcr_non_pmt_rsn_cat
    , False                                 as medicare_will_not_pay
    , 'No Discharge Status'                 as ptnt_dschrg_stus_cat
    , False                                 as patient_discharged
    , False                                 as patient_died_during_claim_period
    , False                                 as patient_remains_in_care_after_claim_period
    , False                                 as clm_pps_bool
    , 0.0                                   as clm_tot_chrg_amt
    , "N/A"                                 as fst_dgns_e_cd 
    , False                                 as claim_has_external_cause 
    , 0                                     as clm_hha_tot_visit_cnt   
    , cast(null as date)                    as clm_admsn_dt 
    , cast(null as integer)                 as rev_cntr_1st_ansi_cd 
    , cast(null as integer)                 as rev_cntr_apc_hipps_cd 
    , 0                                     as clm_utlztn_day_cnt 
    , cast(null as date)                    as nch_bene_dschrg_dt   
    , cast(null as date)                    as clm_hospc_start_dt_id 
    , False                                 as clm_mco_pd_sw
    , False                                 as admission_is_emergency
    , False                                 as admission_is_urgent 
    , False                                 as admission_is_to_trauma_center 
    , False                                 as admission_is_elective
    , 'No Inpatient Admission Source'       as clm_src_ip_admsn_cat
    , 0                                     as clm_pass_thru_per_diem_amt
    , 0                                     as nch_bene_ip_ddctbl_amt 
    , 0                                     as nch_bene_pta_coinsrnc_lblty_am
    , 0                                     as nch_bene_blood_ddctbl_lblty_am 
    , 0                                     as nch_profnl_cmpnt_chrg_amt 
    , 0                                     as clm_tot_pps_cptl_amt 
    , 0                                     as clm_pps_cptl_dsprptnt_shr_amt
    , 0                                     as clm_pps_cptl_excptn_amt
    , 0                                     as clm_pps_cptl_fsp_amt
    , 0                                     as clm_pps_cptl_ime_amt 
    , 0                                     as clm_pps_cptl_outlier_amt 
    , 0                                     as clm_pps_old_cplt_hld_hrmls_amt
    , 0                                     as clm_pps_cptl_drg_wt_num
    , 0                                     as bene_tot_coinsrnc_days_cnt 
    , 0                                     as clm_non_utlztn_days_cnt 
    , 0                                     as nch_blood_pnts_frnshd_qty
    , cast(null as date)                    as nch_vrfd_ncvrd_stay_from_dt
    , cast(null as date)                    as nch_vrfd_ncvrd_stay_thru_dt 
    , cast(null as date)                    as nch_bene_mdcr_bnfts_exhtd_dt_i
    , 'No Outlier'                          as clm_drg_outlier_stay_cat
    , 0                                     as nch_drg_outlier_aprvd_pmt_amt 
    , cast(null as string)                  as admtg_dgns_cd 
    , 0                                     as ime_op_clm_val_amt 
    , 0                                     as dsh_op_clm_val_amt 
    , 0                                     as clm_uncompd_care_pmt_amt 
    , 0                                     as nch_bene_ptb_coinsrnc_amt 
    , 0                                     as nch_bene_partb_ddctbl_amt 
    , 0                                     as clm_op_bene_pmt_amt 
    , 0                                     as clm_op_prvdr_pmt_amt
    , cast(null as date)                    as nch_qlfyd_stay_from_dt 
    , cast(null as date)                    as nch_qlfyd_stay_thru_dt 
    , nch_carr_clm_sbmtd_chrg_amt 
    , nch_clm_bene_pmt_amt 
    , nch_clm_prvdr_pmt_amt
    , 0                                     as nch_ip_ncvrd_chrg_amt 
    , carr_clm_cash_ddctbl_apld_amt 
    , nch_carr_clm_alowd_amt 
    , 0                                     as nch_prmry_pyr_clm_pd_amt
  --diagnoses fields, used only in walk (not main claims fact)
    , icd_dgns_cd1
    , icd_dgns_cd2
    , icd_dgns_cd3
    , icd_dgns_cd4
    , icd_dgns_cd5
    , icd_dgns_cd6
    , icd_dgns_cd7
    , icd_dgns_cd8
    , icd_dgns_cd9
    , icd_dgns_cd10
    , icd_dgns_cd11
    , icd_dgns_cd12
    , cast(null as string)                  as icd_dgns_cd13
    , cast(null as string)                  as icd_dgns_cd14
    , cast(null as string)                  as icd_dgns_cd15
    , cast(null as string)                  as icd_dgns_cd16
    , cast(null as string)                  as icd_dgns_cd17
    , cast(null as string)                  as icd_dgns_cd18
    , cast(null as string)                  as icd_dgns_cd19
    , cast(null as string)                  as icd_dgns_cd20
    , cast(null as string)                  as icd_dgns_cd21
    , cast(null as string)                  as icd_dgns_cd22
    , cast(null as string)                  as icd_dgns_cd23
    , cast(null as string)                  as icd_dgns_cd24
    , cast(null as string)                  as icd_dgns_cd25
    , cast(null as string)                  as icd_dgns_e_cd1
    , cast(null as string)                  as icd_dgns_e_cd2
    , cast(null as string)                  as icd_dgns_e_cd3
    , cast(null as string)                  as icd_dgns_e_cd4
    , cast(null as string)                  as icd_dgns_e_cd5
    , cast(null as string)                  as icd_dgns_e_cd6
    , cast(null as string)                  as icd_dgns_e_cd7
    , cast(null as string)                  as icd_dgns_e_cd8
    , cast(null as string)                  as icd_dgns_e_cd9
    , cast(null as string)                  as icd_dgns_e_cd10
    , cast(null as string)                  as icd_dgns_e_cd11
    , cast(null as string)                  as icd_dgns_e_cd12
from ${ref("clm_dme")} 
group by all 