config {
  type: "table",
  schema: "capstone_intermediaries",
  description: "Lookup for NPI taxonomy - needs further processing before using as lookup",
  }


select 
      string_field_0  as code --confirmed this is serving as primary key; will not bother to rewrite with assertions, just bring into dim_orgs
    , string_field_1  as npi_grouping
    , string_field_2  as classification
    , string_field_3  as specialization
    , string_field_4  as npi_definition
    , string_field_5  as notes
    , string_field_6  as display_name
    , string_field_7  as section
from ${ref("npi_taxonomy")}
where 
  string_field_7 = 'Non-Individual'
  and string_field_0 != 'Code'