config {
  type: "table",
  schema: "capstone_intermediaries",
  description: "Intermediary cleansing for benefits by beneficiary and month, 2025. Note this file only goes until March 2025.",
  assertions: {
    nonNull: ["benefit_mth_key"],
    uniqueKey: ["benefit_mth_key"]
  }
}

select 
      sha256(concat(bene.bene_id,cast(2025 as string),mths.month_num))      as benefit_mth_key
    , bene.bene_id 
    , 2025                                                                  as benefit_year
    , mths.month_num                                                        as benefit_month
    , case 
        when ptc_cntrct_id_01 is not null and mths.month_num = 1 then true 
        when ptc_cntrct_id_02 is not null and mths.month_num = 2 then true 
        when ptc_cntrct_id_03 is not null and mths.month_num = 3 then true 
        else false 
        end                                                                 as has_ptc_for_month
    , case 
        when ptd_cntrct_id_01 is not null and mths.month_num = 1 then true 
        when ptd_cntrct_id_02 is not null and mths.month_num = 2 then true 
        when ptd_cntrct_id_03 is not null and mths.month_num = 3 then true 
        else false 
        end                                                                 as has_ptd_for_month
    , case 
        when rds_ind_01 = 'Y' and mths.month_num = 1 then true 
        when rds_ind_02 = 'Y' and mths.month_num = 2 then true 
        when rds_ind_03 = 'Y' and mths.month_num = 3 then true 
        else false 
        end                                                                 as has_employer_subsidy_for_month
    , case 
        when mths.month_num = 1 then dual_stus_cd_01
        when mths.month_num = 2 then dual_stus_cd_02
        when mths.month_num = 3 then dual_stus_cd_03
        else 'Invalid Row'
        end                                                                 as month_dual_status_code
    , case 
        when dual_stus_cd_01 in ('02','04','08') and mths.month_num = 1 then true 
        when dual_stus_cd_02 in ('02','04','08') and mths.month_num = 2 then true 
        when dual_stus_cd_03 in ('02','04','08') and mths.month_num = 3 then true 
        else false 
        end                                                             as has_full_dual_status
    , case 
        when dual_stus_cd_01 in ('01','03','05','06') and mths.month_num = 1 then true 
        when dual_stus_cd_02 in ('01','03','05','06') and mths.month_num = 2 then true 
        when dual_stus_cd_03 in ('01','03','05','06') and mths.month_num = 3 then true 
        else false 
        end                                                             as has_partial_dual_status
    , case 
        when dual_stus_cd_01 = '01' and mths.month_num = 1 then true 
        when dual_stus_cd_02 = '01' and mths.month_num = 2 then true 
        when dual_stus_cd_03 = '01' and mths.month_num = 3 then true 
        else false 
        end                                                             as is_qmb_only
    , case 
        when cst_shr_grp_cd_01 in (1,2,3) and mths.month_num = 1 then 100 
        when cst_shr_grp_cd_02 in (1,2,3) and mths.month_num = 2 then 100 
        when cst_shr_grp_cd_03 in (1,2,3) and mths.month_num = 3 then 100 
        else 0 
        end                                                             as cost_share_premium_subsidy_percent
    , case 
        when mths.month_num = 1
            then 
                case 
                    when cst_shr_grp_cd_01 = 1
                        then 'no copay' 
                    when cst_shr_grp_cd_01 = 2
                        then 'low copay'
                    when cst_shr_grp_cd_01 = 3
                        then 'high copay'
                    else 'Not Applicable'
                    end
        when mths.month_num = 2
            then 
                case 
                    when cst_shr_grp_cd_02 = 1
                        then 'no copay' 
                    when cst_shr_grp_cd_02 = 2
                        then 'low copay'
                    when cst_shr_grp_cd_02 = 3
                        then 'high copay'
                    else 'Not Applicable'
                    end
        when mths.month_num = 3
            then 
                case 
                    when cst_shr_grp_cd_03 = 1
                        then 'no copay' 
                    when cst_shr_grp_cd_03 = 2
                        then 'low copay'
                    when cst_shr_grp_cd_03 = 3
                        then 'high copay'
                    else 'Not Applicable'
                    end
        else 'Invalid Row'
        end                                                         as cost_share_copay_cat
from ${ref("bene_25")} bene
cross join ${ref("seed_months_numeric")} mths 
where mths.month_num in (1,2,3)
